blank_issues_enabled: true
contact_links:
  - name: General Slack Help
    url: https://mediamonks.slack.com/#muban
    about: Please ask and answer questions here.
  - name: Muban Dev Slack Conversations
    url: https://mediamonks.slack.com/#muban-dev
    about: Discuss ideas, issues and solutions.
  - name: Todo list & Progress
    url: https://github.com/mubanjs/muban-skeleton/projects/1
    about: Kanban-style board with todos and progress. Have a rough idea? Add it here!
  - name: Discussions
    url: https://github.com/mubanjs/muban-skeleton/discussions
    about: Questions, Ideas, Discussions and Share
  - name: Skeleton Docs
    url: https://mubanjs.github.io/muban-skeleton/
    about: Please read the docs first
  - name: Muban Docs
    url: https://mubanjs.github.io/muban/
    about: Please read the docs first
